import { palette } from "./palette";

export const themeColors = {
  focusBorder: palette.accent.blue,
  foreground: palette.fg.primary,
  disabledForeground: palette.fg.disabled,
  "widget.shadow": palette.ui.shadow,
  "selection.background": palette.bg.selection,
  "descriptionForeground": palette.fg.muted,
  "errorForeground": palette.semantic.error,
  "icon.foreground": palette.fg.muted,

  "window.activeBorder": palette.bg.app,
  "window.inactiveBorder": palette.bg.app,

  "editor.background": palette.bg.editor,
  "editor.foreground": palette.fg.primary,
  "editorLineNumber.foreground": palette.fg.subtle,
  "editorLineNumber.activeForeground": palette.fg.muted,
  "editorCursor.foreground": palette.accent.blue,
  "editor.selectionBackground": palette.bg.selection,
  "editor.inactiveSelectionBackground": palette.bg.selectionInactive,
  "editor.selectionHighlightBackground": palette.ui.purpleAlpha22,
  "editor.wordHighlightBackground": palette.ui.blueAlpha22,
  "editor.wordHighlightStrongBackground": palette.ui.purpleAlpha22,
  "editor.findMatchBackground": palette.ui.yellowAlpha68,
  "editor.findMatchHighlightBackground": palette.ui.yellowAlpha34,
  "editor.findRangeHighlightBackground": palette.ui.yellowAlpha26,
  "editor.hoverHighlightBackground": palette.ui.whiteAlpha10,
  "editor.lineHighlightBackground": palette.bg.currentLine,
  "editor.lineHighlightBorder": palette.ui.transparent,
  "editorIndentGuide.background1": palette.ui.whiteAlpha12,
  "editorIndentGuide.activeBackground1": palette.ui.whiteAlpha42,
  "editorWhitespace.foreground": palette.ui.whiteAlpha16,
  "editorRuler.foreground": palette.ui.whiteAlpha18,
  "editorBracketMatch.background": palette.ui.blueAlpha24,
  "editorBracketMatch.border": palette.ui.blueAlpha66,
  "editorLink.activeForeground": palette.accent.cyan,
  "editor.rangeHighlightBackground": palette.ui.blueAlpha31,
  "editor.rangeHighlightBorder": palette.ui.transparent,
  "editorUnicodeHighlight.border": palette.semantic.warning,
  "editorCodeLens.foreground": palette.fg.subtle,

  "editorGroup.border": palette.bg.app,
  "editorGroupHeader.tabsBackground": palette.bg.app,
  "editorGroupHeader.tabsBorder": palette.bg.app,
  "editorGroupHeader.noTabsBackground": palette.bg.app,

  "tab.activeBackground": palette.bg.app,
  "tab.inactiveBackground": palette.bg.app,
  "tab.activeForeground": palette.fg.primary,
  "tab.inactiveForeground": palette.fg.subtle,
  "tab.border": palette.bg.app,
  "tab.activeBorder": palette.ui.transparent,
  "tab.activeBorderTop": palette.ui.transparent,
  "tab.unfocusedActiveBorder": palette.ui.transparent,
  "tab.unfocusedActiveBorderTop": palette.ui.transparent,
  "tab.lastPinnedBorder": palette.bg.app,
  "tab.hoverBackground": palette.bg.hover,
  "tab.unfocusedHoverBackground": palette.bg.hover,

  "sideBar.background": palette.bg.sidebar,
  "sideBar.foreground": palette.fg.muted,
  "sideBar.border": palette.bg.app,
  "sideBarTitle.foreground": palette.fg.primary,
  "sideBarSectionHeader.background": palette.bg.app,
  "sideBarSectionHeader.foreground": palette.fg.primary,
  "sideBarSectionHeader.border": palette.bg.app,

  "activityBar.background": palette.bg.app,
  "activityBar.foreground": palette.fg.primary,
  "activityBar.inactiveForeground": palette.fg.subtle,
  "activityBar.border": palette.bg.app,
  "activityBar.activeBorder": palette.accent.blue,
  "activityBar.activeBackground": palette.ui.transparent,
  "activityBarBadge.background": palette.accent.purple,
  "activityBarBadge.foreground": palette.fg.inverse,

  "titleBar.activeBackground": palette.bg.app,
  "titleBar.inactiveBackground": palette.bg.app,
  "titleBar.activeForeground": palette.fg.primary,
  "titleBar.inactiveForeground": palette.fg.subtle,
  "titleBar.border": palette.bg.app,

  "statusBar.background": palette.bg.app,
  "statusBar.foreground": palette.fg.primary,
  "statusBar.border": palette.bg.app,
  "statusBar.noFolderBackground": palette.bg.app,
  "statusBar.debuggingBackground": palette.ui.debugStatus,
  "statusBar.debuggingForeground": palette.fg.primary,
  "statusBarItem.hoverBackground": palette.bg.hover,
  "statusBarItem.compactHoverBackground": palette.bg.hover,
  "statusBarItem.prominentBackground": palette.bg.overlay,
  "statusBarItem.prominentHoverBackground": palette.bg.hover,
  "statusBarItem.remoteBackground": palette.accent.purple,
  "statusBarItem.remoteForeground": palette.fg.inverse,
  "statusBarItem.errorBackground": palette.ui.errorAlpha38,
  "statusBarItem.warningBackground": palette.ui.warningAlpha38,

  "panel.background": palette.bg.panel,
  "panel.border": palette.bg.app,
  "panelTitle.activeForeground": palette.fg.primary,
  "panelTitle.inactiveForeground": palette.fg.subtle,
  "panelTitle.activeBorder": palette.accent.blue,
  "panelSection.border": palette.bg.app,
  "panelSectionHeader.background": palette.bg.panel,
  "panelSectionHeader.foreground": palette.fg.primary,
  "panelSectionHeader.border": palette.bg.app,

  "terminal.background": palette.bg.panel,
  "terminal.foreground": palette.fg.primary,
  "terminalCursor.background": palette.fg.primary,
  "terminalCursor.foreground": palette.accent.blue,
  "terminal.ansiBlack": palette.ansi.black,
  "terminal.ansiRed": palette.ansi.red,
  "terminal.ansiGreen": palette.ansi.green,
  "terminal.ansiYellow": palette.ansi.yellow,
  "terminal.ansiBlue": palette.ansi.blue,
  "terminal.ansiMagenta": palette.ansi.magenta,
  "terminal.ansiCyan": palette.ansi.cyan,
  "terminal.ansiWhite": palette.ansi.white,
  "terminal.ansiBrightBlack": palette.ansi.brightBlack,
  "terminal.ansiBrightRed": palette.ansi.brightRed,
  "terminal.ansiBrightGreen": palette.ansi.brightGreen,
  "terminal.ansiBrightYellow": palette.ansi.brightYellow,
  "terminal.ansiBrightBlue": palette.ansi.brightBlue,
  "terminal.ansiBrightMagenta": palette.ansi.brightMagenta,
  "terminal.ansiBrightCyan": palette.ansi.brightCyan,
  "terminal.ansiBrightWhite": palette.ansi.brightWhite,

  "input.background": palette.bg.input,
  "input.foreground": palette.fg.primary,
  "input.border": palette.bg.overlay,
  "input.placeholderForeground": palette.fg.subtle,
  "inputOption.activeBorder": palette.accent.blue,
  "inputValidation.errorBackground": palette.ui.errorAlpha26,
  "inputValidation.errorBorder": palette.semantic.error,
  "inputValidation.warningBackground": palette.ui.yellowAlpha26,
  "inputValidation.warningBorder": palette.semantic.warning,
  "inputValidation.infoBackground": palette.ui.infoAlpha26,
  "inputValidation.infoBorder": palette.semantic.info,

  "dropdown.background": palette.bg.input,
  "dropdown.foreground": palette.fg.primary,
  "dropdown.border": palette.bg.overlay,
  "list.activeSelectionBackground": palette.ui.blueAlpha45,
  "list.activeSelectionForeground": palette.fg.primary,
  "list.inactiveSelectionBackground": palette.ui.blueAlpha29,
  "list.inactiveSelectionForeground": palette.fg.primary,
  "list.hoverBackground": palette.bg.hover,
  "list.hoverForeground": palette.fg.primary,
  "list.focusBackground": palette.ui.blueAlpha48,
  "list.focusForeground": palette.fg.primary,
  "list.highlightForeground": palette.accent.cyan,
  "list.errorForeground": palette.semantic.error,
  "list.warningForeground": palette.semantic.warning,

  "scrollbar.shadow": palette.ui.blackAlpha40,
  "scrollbarSlider.background": palette.ui.whiteAlpha21,
  "scrollbarSlider.hoverBackground": palette.ui.whiteAlpha35,
  "scrollbarSlider.activeBackground": palette.ui.whiteAlpha74,

  "editorWidget.background": palette.bg.elevated,
  "editorWidget.foreground": palette.fg.primary,
  "editorWidget.border": palette.bg.overlay,
  "peekView.border": palette.bg.overlay,
  "peekViewEditor.background": palette.bg.editor,
  "peekViewEditorGutter.background": palette.bg.editor,
  "peekViewResult.background": palette.bg.elevated,
  "peekViewResult.selectionBackground": palette.ui.blueAlpha24,
  "peekViewResult.selectionForeground": palette.fg.primary,
  "peekViewTitle.background": palette.bg.panel,
  "peekViewTitleLabel.foreground": palette.fg.primary,
  "peekViewTitleDescription.foreground": palette.fg.subtle,

  "notificationCenterHeader.background": palette.bg.elevated,
  "notificationCenterHeader.foreground": palette.fg.primary,
  "notifications.background": palette.bg.elevated,
  "notifications.foreground": palette.fg.primary,
  "notifications.border": palette.bg.overlay,

  "badge.background": palette.accent.purple,
  "badge.foreground": palette.fg.inverse,
  "progressBar.background": palette.accent.blue,

  "editorError.foreground": palette.semantic.error,
  "editorWarning.foreground": palette.semantic.warning,
  "editorInfo.foreground": palette.semantic.info,
  "editorHint.foreground": palette.accent.cyan,
  "problemsErrorIcon.foreground": palette.semantic.error,
  "problemsWarningIcon.foreground": palette.semantic.warning,
  "problemsInfoIcon.foreground": palette.semantic.info,

  "gitDecoration.addedResourceForeground": palette.git.added,
  "gitDecoration.modifiedResourceForeground": palette.git.modified,
  "gitDecoration.deletedResourceForeground": palette.git.deleted,
  "gitDecoration.untrackedResourceForeground": palette.git.untracked,
  "gitDecoration.ignoredResourceForeground": palette.git.ignored,
  "gitDecoration.conflictingResourceForeground": palette.git.conflicting,
  "gitDecoration.submoduleResourceForeground": palette.git.submodule,
} as const;
